const Database = require('better-sqlite3');
const path = require('path');
const dbPath = path.join(__dirname, 'roar-mma', 'data', 'roarmma.db');
console.log('DB Path:', dbPath);
const db = new Database(dbPath);
const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all();
console.log('Tables:', tables.map(t => t.name));
const staff = db.prepare('SELECT id, name, email, role FROM staff').all();
console.log('Staff:', JSON.stringify(staff, null, 2));
db.close();
