const express = require('express');
const { authenticateToken, requirePermission } = require('../middleware/auth');
const { getDatabase } = require('../db/connection');
const router = express.Router();

function renderWaiverHTML(waiver, template, member) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Waiver - ${member.first_name} ${member.last_name}</title>
<style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;padding:20px;color:#222;line-height:1.6}
h1{text-align:center;font-size:22px;border-bottom:2px solid #000;padding-bottom:10px}
.meta{font-size:12px;color:#666;text-align:center;margin-bottom:20px}
.content{white-space:pre-wrap;margin:20px 0;padding:15px;background:#f9f9f9;border:1px solid #ddd;font-size:13px}
.signature{text-align:center;margin:30px 0}
.signature img{max-width:300px;border:1px solid #ccc;padding:10px;background:#fff}
.footer{text-align:center;font-size:11px;color:#999;border-top:1px solid #ddd;padding-top:15px;margin-top:30px}
</style></head><body>
<h1>Roar MMA - Waiver / Release of Liability</h1>
<div class="meta">Signed: ${new Date(waiver.signed_at).toLocaleString()} | IP: ${waiver.ip_address || 'N/A'}</div>
<div class="meta">Member: ${member.first_name} ${member.last_name} (ID: ${member.id})</div>
<div class="meta">Template: ${template?.name || 'Unknown'}</div>
<div class="content">${template?.body_text || 'No template text available.'}</div>
${waiver.guardian_name ? `<p><strong>Signed by guardian:</strong> ${waiver.guardian_name} (${waiver.guardian_relation})</p>` : ''}
<div class="signature"><p><strong>Signature:</strong></p><img src="${waiver.signature_data}" alt="Signature" /></div>
<div class="footer">This is a legally binding document. Generated by Roar MMA Management System.</div>
</body></html>`;
}

function renderInvoiceHTML(member, transactions) {
  const total = transactions.reduce((s, t) => s + (t.amount || 0), 0);
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Invoice - ${member.first_name} ${member.last_name}</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:20px;color:#222}
.header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #dc2626;padding-bottom:15px;margin-bottom:20px}
h1{font-size:24px;color:#dc2626;margin:0}
.address{font-size:12px;color:#666}
.member-info{font-size:13px;margin-bottom:20px}
table{width:100%;border-collapse:collapse;margin:15px 0}
th{background:#f3f4f6;text-align:left;padding:8px 10px;font-size:12px;text-transform:uppercase;color:#666}
td{padding:8px 10px;border-bottom:1px solid #e5e7eb;font-size:13px}
.total-row{font-weight:bold;font-size:15px}
.total-row td{border-top:2px solid #000;padding-top:10px}
.footer{text-align:center;font-size:11px;color:#999;margin-top:30px;border-top:1px solid #ddd;padding-top:15px}
</style></head><body>
<div class="header"><div><h1>INVOICE</h1><p class="address">Roar MMA<br>Rockingham, WA<br>ABN: XX-XXX-XXX</p></div><div class="address"><p>Date: ${new Date().toLocaleDateString()}</p></div></div>
<div class="member-info"><strong>Member:</strong> ${member.first_name} ${member.last_name}<br><strong>Email:</strong> ${member.email || 'N/A'}<br><strong>Phone:</strong> ${member.phone || 'N/A'}</div>
<table><thead><tr><th>Date</th><th>Description</th><th>Type</th><th>Status</th><th style="text-align:right">Amount</th></tr></thead>
<tbody>${transactions.map(t => `<tr><td>${new Date(t.processed_at || t.created_at).toLocaleDateString()}</td><td>${t.description || '—'}</td><td>${(t.type || 'other').replace(/_/g, ' ')}</td><td>${t.status}</td><td style="text-align:right">$${(t.amount || 0).toFixed(2)}</td></tr>`).join('')}</tbody>
<tfoot><tr class="total-row"><td colspan="4" style="text-align:right">Total</td><td style="text-align:right">$${total.toFixed(2)}</td></tr></tfoot></table>
<div class="footer">This is a computer-generated invoice. For inquiries contact Roar MMA management.</div>
</body></html>`;
}

router.get('/waiver/:id', authenticateToken, requirePermission('members:read'), (req, res) => {
  try {
    const db = getDatabase();
    const waiver = db.prepare('SELECT * FROM member_waivers WHERE id = ?').get(parseInt(req.params.id));
    if (!waiver) return res.status(404).json({ error: 'Waiver not found' });
    const member = db.prepare('SELECT * FROM members WHERE id = ?').get(waiver.member_id);
    const template = db.prepare('SELECT * FROM waiver_templates WHERE id = ?').get(waiver.template_id);
    res.setHeader('Content-Type', 'text/html');
    res.send(renderWaiverHTML(waiver, template, member));
  } catch (error) { res.status(500).json({ error: 'Failed to generate waiver PDF' }); }
});

router.get('/invoice/:memberId', authenticateToken, requirePermission('members:read'), (req, res) => {
  try {
    const db = getDatabase();
    const member = db.prepare('SELECT * FROM members WHERE id = ?').get(parseInt(req.params.memberId));
    if (!member) return res.status(404).json({ error: 'Member not found' });
    const transactions = db.prepare("SELECT * FROM transactions WHERE member_id = ? AND status = 'completed' ORDER BY created_at DESC").all(member.id);
    res.setHeader('Content-Type', 'text/html');
    res.send(renderInvoiceHTML(member, transactions));
  } catch (error) { res.status(500).json({ error: 'Failed to generate invoice' }); }
});

module.exports = router;
